name = "gradient_supremum"
version = "0.1.0"
defaultTargets = ["GradientSupremum"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[require]]
name = "fixed-point-theorems"
git = "https://github.com/harfe/fixed-point-theorems-lean4"
rev = "770940ddf9878cf61952ed53d910b92bca841838"

[[lean_lib]]
name = "GradientSupremum"
