name = "gradient_supremum"
version = "0.2.0"
defaultTargets = ["GradientSupremum"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "GradientSupremum"
